name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check locale
      run: locale -a
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache
      uses: actions/cache@v1.0.0
      with:
        path: ~/.m2
        key: ${{ hashFiles('pom.xml') }}
    - name: Build with Maven
      run: mvn -B verify --file pom.xml -Dmaven.javadoc.failOnError=false
